package com.example.travelactivityapp.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;

@Entity // This class is an entity
@Data // Lombok annotation to generate getters and setters
@NoArgsConstructor // Lombok annotation to generate a no-args constructor
@AllArgsConstructor // Lombok annotation to generate an all-args constructor
@Builder // Lombok annotation to generate a builder
public class Tag {

    @Id // This field is the primary key
    @GeneratedValue(strategy = GenerationType.SEQUENCE) // This field is generated by the database
    private Long id;

    private String tagName;

    @ManyToMany(mappedBy = "tags") // This field is mapped by the itineraries
    @JsonIgnore // This field is ignored in the JSON response
    private Set<Itinerary> itineraries = new HashSet<>(); 

    @ManyToMany(mappedBy = "tags")
    @JsonIgnore
    private Set<Activity> activities = new HashSet<>();

}
